### ISSUE TITLE
메뉴가 길면 보이는 스크롤바 정리

### ISSUE THREAD

**Issue by eruhoon** [eruhoon/mycast-web-client#22]
![image](https://user-images.githubusercontent.com/8344744/84513071-e2cfd580-ad03-11ea-8354-5a689ee8370d.png)
![image](https://user-images.githubusercontent.com/8344744/84513076-e5cac600-ad03-11ea-88db-50e46f9d1308.png)

**Comment by w2story** [comment]
해당 부분 처리 완료
