### ISSUE TITLE
드래그앤 드롭 url version

### ISSUE THREAD

**Issue by eruhoon** [eruhoon/mycast-web-client#25]
![image](https://user-images.githubusercontent.com/8344744/84595770-b4353480-ae94-11ea-8478-e108bb6f0be8.png)

**Comment by eruhoon** [comment]
아마 웹에도 로딩만되면 가능할듯

**Comment by z1z2z3z4** [comment]
텍스트 붙여넣기에도 작동되는거 같습니다.

**Comment by eruhoon** [comment]
이제 텍스트복붙에서 안됨
