### ISSUE TITLE
TwitchClipPack 구현

### ISSUE THREAD

**Issue by eruhoon** [eruhoon/mycast-web-client#34]
TwitchClipPack 구현

**Comment by eruhoon** [comment]
2e4f191f0c09f4d24d202a4f0aea27a01a8cb248

BaseFile Created

**Comment by eruhoon** [comment]
55ed1c07d86e3d08d970e6244ee8c125bb6267f3
bind complete

**Comment by eruhoon** [comment]
디자인 잡아주시면될거같습니다

**Comment by w2story** [comment]
디자인 완료
