### ISSUE TITLE
트위치 명령어 및 공유링크

### ISSUE THREAD

**Issue by z1z2z3z4** [eruhoon/mycast-web-client#5]
![image](https://user-images.githubusercontent.com/46558914/82057433-49120a00-96fe-11ea-9f63-47f656311efc.png)
![image](https://user-images.githubusercontent.com/46558914/82057458-4fa08180-96fe-11ea-8a78-5ddcfa158fb8.png)

트위치 링크를 채팅창에 띄웠을때의 작동 미완성.

**Comment by eruhoon** [comment]
커밋참조
