### ISSUE TITLE
pc용 일정크기 이하에서 방송목록이 안보임

### ISSUE THREAD

**Issue by z1z2z3z4** [eruhoon/mycast-web-client#50]
https://github.com/eruhoon/mycast-web-client/commit/985cb8a5aa5a26de74c2c5002c464822f4a44f96
커밋된 파일 중
src/app/views/main-page/side-bar/side-bar.component.scss
에서
![image](https://user-images.githubusercontent.com/46558914/85676500-9d4ad980-b701-11ea-8599-c3ff1445d3c8.png)
부분 때문이라고 보여짐

**Comment by w2story** [comment]
미디어 쿼리 적용을 통하여 해당 인치수 이하로 적용 처리 되는 구간이 있으나
해당부분 모바일 체커 ts코드와 겹치는 부분이 확인됩니다.
이부분은 해당 모바일 ts코드 제거나 pc 부분 추가 처리를 통해 가능합니다.

**Comment by w2story** [comment]
수정완료

**Comment by eruhoon** [comment]
ㅋㅋ이제봄 ㄱㅅㄱㅅ
