### ISSUE TITLE
::명령어 default 시 수정요청

### ISSUE THREAD

**Issue by z1z2z3z4** [eruhoon/mycast-web-client#6]
![image](https://user-images.githubusercontent.com/46558914/82057742-bfaf0780-96fe-11ea-88d7-fb69a110aff3.png)
.
.
![image](https://user-images.githubusercontent.com/46558914/82057752-c3428e80-96fe-11ea-8de1-dfab4b7e0aff.png)

./src/app/models/socket/chat-request/ChatRequestFactory.ts

지금은 ::입력 시 없는 명령어일 경우 ::까지의 텍스트(match[1] or rawType)가 사라지고 
::뒤의 텍스트(match[2] or rawMsg)만 나옴.

2번째 이미지의 default시 **rawMsg 대신 rawText로** 하면 원본이 다 보일것 같음.

**Comment by eruhoon** [comment]
![image](https://user-images.githubusercontent.com/8344744/82114141-d48aaa00-9795-11ea-8fd2-2b5ce42d49d6.png)
수정완료. 내일 될듯
