### ISSUE TITLE
gpc link 오류

### ISSUE THREAD

**Issue by z1z2z3z4** [eruhoon/mycast-web-client#66]
gpc로 나무위키 링크 시

![dd390428c664fc611e7292fb1304b7bb](https://user-images.githubusercontent.com/46558914/96860345-9a88a700-149d-11eb-96ac-62ac4736652c.png)
위와 같은 에러가 뜨는 사람이 있음

![07135b5bf92bb22d5ecdd57aba8c44ea](https://user-images.githubusercontent.com/46558914/96860378-a5433c00-149d-11eb-9515-2768d50d5830.png)

나무위키 말고도 다른 사이트도 있을 수 있음.

**Comment by eruhoon** [comment]
새창으로뜨게 바꿈
