### ISSUE TITLE
포토 페이지 스크롤링시 검색어가 풀림

### ISSUE THREAD

**Issue by w2story** [eruhoon/mycast-web-client#67]
[https://i.imgur.com/h8HdXqe.gif](url)

포토에서 이미지 검색시 스크롤링시 검색어가 풀리면서 스크롤링이 되는 현상이 발견됬습니다.

아마 페이지를 불러오면서 추가 된 값이 아닌 기존 값으로 처리 되는것 같습니다.

**Comment by z1z2z3z4** [comment]
![7a278ad54c2532795f9406624fa6b65f](https://user-images.githubusercontent.com/46558914/97538885-7c262c80-1a04-11eb-92b1-9a01b17293fd.gif)

**Comment by eruhoon** [comment]
해결했으용
