### ISSUE TITLE
방송 hover 썸네일 없음

### ISSUE THREAD

**Issue by caesar-mo** [eruhoon/mycast-web-client#7]
![image](https://user-images.githubusercontent.com/59224354/82061964-5af6ab80-9704-11ea-800d-feff4953c216.png)
이전 버전에서는 이런식으로 나오는 기능입니다.
썸네일에 묶여있는 ui들도 같이 없으니까
1. 채팅창에 링크하기
2. 새 창에서 보기
3. 방송 즐겨찾기
위의 기능들도 사용이 안됩니다.

![image](https://user-images.githubusercontent.com/59224354/82062255-cf314f00-9704-11ea-84ad-c313d12a4538.png)
지금 버전에서도 메인 화면에 떠있는 방송들은 이렇게 나오는데, 트위치/카카오 탭에 있는 방송들은 안나옵니다.

**Comment by w2story** [comment]
css 부분 스크롤 처리로 인하여
이전 부분처럼 나오게 하려면 js를 통해서 x,y값을 떠서 처리를 해야될것같습니다.
그외적인 방안으로는 마우스를 올리면 상단에 뜨게 하는 방안을 검토해보겠습니다.

**Comment by w2story** [comment]
모바일 부분은 추가적인 처리가 되어서 썸네일과 같이 나오지만 pc에서는 썸네일이 나오지 않아
추후 따로 페이지를빼서 처리하는 방안을 검토 부탁드립니다.

**Comment by w2story** [comment]
![image](https://user-images.githubusercontent.com/39890301/85943042-6aeee580-b968-11ea-9d7c-8a52f9689642.png)

디자인은 처리 완

**Comment by eruhoon** [comment]
이것도 잇긴하니 닫
