### ISSUE TITLE
어둡게 하였을때 유저리스트 css 수정 요청

### ISSUE THREAD

**Issue by z1z2z3z4** [eruhoon/mycast-web-client#9]
[src/app/views/chat/] 안의

![image](https://user-images.githubusercontent.com/46558914/82518589-aa046c80-9b5a-11ea-9b54-1050704f415f.png)

수정이 누락된거 같음.

![image](https://user-images.githubusercontent.com/46558914/82518708-e637cd00-9b5a-11ea-9065-18bd4fda9d69.png)

**Comment by w2story** [comment]
수정완료
